---
- name: Fetch Java Version
  shell: "rpm -q --whatprovides java | cut -d'-' -f2 warn=false"
  register: res
- debug:
   msg: "{{res.stdout}}"
- name: copy file
  file:
   src: /home/mserver/ansible-poc/test.txt
   dest: /tmp/test.txt
   state: hard
   mode: u+rw,g-wx,o-rwx
- name: Display Content of file
  shell: "cat /tmp/test.txt"
  register: r
- debug:
   msg: "Content : {{r.stdout}}"
