---
- name: Fetch Software Versions
  shell: "echo {{item}}| tr -d '\n' echo "-" | tr -d '\n'  && rpm -q --whatprovides {{item}} | cut -d'-' -f2  warn=false"
  register: r
  with_items: "{{softwares}}"
  ignore_errors: yes
  failed_when: false

- debug: msg="{{r.results|map(attribute='stdout')| list }} "
- name: Push package to target host
  copy:
   src: "/home/mserver/ansible-poc/test.txt"
   dest: /tmp/test.txt
   mode: u+rw,g-wx,o-rwx
- name: Display Content of file
  shell: "cat /tmp/test.txt"
  register: r
- debug:
   msg: "Content : {{r.stdout}}"
