---
- name: Fetch Software Versions
  shell: "echo {{item}}  && rpm -q --whatprovides {{item}} | cut -d'-' -f2 | tr -d '\n' warn=false"
  register: r
  with_items: "{{softwares}}"
  ignore_errors: yes
  failed_when: false

- debug: msg="{{r.results|map(attribute='stdout')| list }} "
